# Generated by Django 5.0.3 on 2024-05-08 02:54

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_obesity', multiselectfield.db.fields.MultiSelectField(choices=[('nao', 'Não'), ('pais', 'Pais'), ('avos', 'Avós'), ('tios', 'Tios'), ('irmaos', 'Irmãos')], max_length=25, verbose_name='Obesidade na familia')),
                ('family_hypertension', multiselectfield.db.fields.MultiSelectField(choices=[('nao', 'Não'), ('pais', 'Pais'), ('avos', 'Avós'), ('tios', 'Tios'), ('irmaos', 'Irmãos')], max_length=25, verbose_name='Hipertensão na familia')),
                ('family_diabetes', multiselectfield.db.fields.MultiSelectField(choices=[('nao', 'Não'), ('pais', 'Pais'), ('avos', 'Avós'), ('tios', 'Tios'), ('irmaos', 'Irmãos')], max_length=25, verbose_name='Diabetes na familia')),
                ('family_coronary', multiselectfield.db.fields.MultiSelectField(choices=[('nao', 'Não'), ('pais', 'Pais'), ('avos', 'Avós'), ('tios', 'Tios'), ('irmaos', 'Irmãos')], max_length=25, verbose_name='Doença coronariana na familia')),
                ('family_avc', multiselectfield.db.fields.MultiSelectField(choices=[('nao', 'Não'), ('pais', 'Pais'), ('avos', 'Avós'), ('tios', 'Tios'), ('irmaos', 'Irmãos')], max_length=25, verbose_name='AVC na familia')),
                ('family_cancer', multiselectfield.db.fields.MultiSelectField(choices=[('nao', 'Não'), ('pais', 'Pais'), ('avos', 'Avós'), ('tios', 'Tios'), ('irmaos', 'Irmãos')], max_length=25, verbose_name='Cancêr na familia')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Histórico Familiar',
                'verbose_name_plural': 'Históricos Familiares',
            },
        ),
    ]
