# Generated by Django 5.0.3 on 2024-05-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_historicofamiliar'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcoesFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Sintomas gastrointestinais pós-cirurgicos',
                'verbose_name_plural': 'Sintomas gastrointestinais pós-cirurgicos',
            },
        ),
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='family_avc',
        ),
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='family_cancer',
        ),
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='family_coronary',
        ),
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='family_diabetes',
        ),
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='family_hypertension',
        ),
        migrations.RemoveField(
            model_name='historicofamiliar',
            name='family_obesity',
        ),
        migrations.AddField(
            model_name='historicofamiliar',
            name='family_avc',
            field=models.ManyToManyField(related_name='family_avc', to='registros.opcoesfamilia', verbose_name='AVC na familia'),
        ),
        migrations.AddField(
            model_name='historicofamiliar',
            name='family_cancer',
            field=models.ManyToManyField(related_name='family_cancer', to='registros.opcoesfamilia', verbose_name='Cancêr na familia'),
        ),
        migrations.AddField(
            model_name='historicofamiliar',
            name='family_coronary',
            field=models.ManyToManyField(related_name='family_coronary', to='registros.opcoesfamilia', verbose_name='Doença coronariana na familia'),
        ),
        migrations.AddField(
            model_name='historicofamiliar',
            name='family_diabetes',
            field=models.ManyToManyField(related_name='family_diabetes', to='registros.opcoesfamilia', verbose_name='Diabetes na familia'),
        ),
        migrations.AddField(
            model_name='historicofamiliar',
            name='family_hypertension',
            field=models.ManyToManyField(related_name='family_hypertension', to='registros.opcoesfamilia', verbose_name='Hipertensão na familia'),
        ),
        migrations.AddField(
            model_name='historicofamiliar',
            name='family_obesity',
            field=models.ManyToManyField(related_name='family_obesity', to='registros.opcoesfamilia', verbose_name='Obesidade na familia'),
        ),
    ]
