# Generated by Django 5.0.3 on 2024-03-30 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'verbose_name_plural': 'Horários de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('ocupation', models.CharField(max_length=255, verbose_name='Ocupação')),
                ('cellphone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_home', models.CharField(max_length=150, verbose_name='Endereço')),
                ('income_family', models.CharField(choices=[('sem renda', 'Sem renda'), ('1 a 2', '1 a 2'), ('2 a 4', '2 a 4'), ('4 a 10', '4 a 10'), ('10 a 20', '10 a 20'), ('20 ou mais', '20 ou mais')], max_length=25, verbose_name='Renda Familiar (em salarios minimos)')),
                ('housing_type', models.CharField(choices=[('própria', 'Própria'), ('alugada', 'Alugada'), ('cedida', 'Cedida')], max_length=25, verbose_name='Tipo de moradia')),
                ('residents_number', models.PositiveSmallIntegerField(verbose_name='Quantidade de moradores')),
                ('offspring_number', models.PositiveSmallIntegerField(verbose_name='Quantidade de filhos')),
                ('education', models.CharField(choices=[('analfabeto/analfabeto-funcional', 'Analfabeto/Analfabeto Funcional'), ('ensino-fundamental-incompleto', 'Ensino Fundamental Incompleto'), ('ensino-fundamental-completo', 'Ensino Fundamental Completo'), ('ensino-médio-incompleto', 'Ensino Médio Incompleto'), ('ensino-médio-completo', 'Ensino Médio Completo'), ('ensino-superior-incompleto', 'Ensino Superior Incompleto'), ('ensino-superior-completo', 'Ensino Superior Completo')], max_length=50, verbose_name='Escolaridade')),
                ('skin', models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('parda', 'Parda'), ('indigena', 'Indigena')], max_length=25, verbose_name='Pele')),
                ('civil_state', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado/amasiado', 'Casado/Amasiado'), ('separado/divorciado', 'Separado/Divorciado'), ('viúvo', 'Viúvo')], max_length=50, verbose_name='Estado civil')),
                ('reason_consultation', models.CharField(choices=[('acompanhamento nutricional', 'Acompanhamento nutricional'), ('laudo nutricional', 'Laudo nutricional'), ('acompanhamento e laudo nutricional', 'Acompanhamento e Laudo nutricional')], max_length=50, verbose_name='Motivo da consulta')),
                ('address_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cidade', verbose_name='Cidade')),
                ('work_hours', models.ManyToManyField(related_name='horarios', to='pacientes.horariotrabalho', verbose_name='Horário de Trabalho')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=48, verbose_name='Nome do contato')),
                ('description', models.CharField(max_length=30, verbose_name='Descrição')),
                ('cellphone_number', models.CharField(max_length=20, verbose_name='Telefone Celular')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
