# Generated by Django 5.0.1 on 2024-03-22 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='address_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='contato',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
