# Generated by Django 5.0.3 on 2024-05-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Local de Refeição',
                'verbose_name_plural': 'Locais de Refeições',
            },
        ),
        migrations.CreateModel(
            name='QuemPrepara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Quem prepara as refeições',
                'verbose_name_plural': 'Quem prepara as refeições',
            },
        ),
        migrations.CreateModel(
            name='TipoAlcool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de bebida Alcoólica',
                'verbose_name_plural': 'Tipos de bebidas Alcoólicas',
            },
        ),
        migrations.RemoveField(
            model_name='formbase',
            name='alcoholic_type',
        ),
        migrations.RemoveField(
            model_name='formbase',
            name='meal_place',
        ),
        migrations.RemoveField(
            model_name='formbase',
            name='who_prepares',
        ),
        migrations.AddField(
            model_name='formbase',
            name='alcoholic_type',
            field=models.ManyToManyField(blank=True, to='consultas.tipoalcool', verbose_name='Qual bebida'),
        ),
        migrations.AddField(
            model_name='formbase',
            name='meal_place',
            field=models.ManyToManyField(to='consultas.localrefeicao', verbose_name='Onde realiza refeições'),
        ),
        migrations.AddField(
            model_name='formbase',
            name='who_prepares',
            field=models.ManyToManyField(to='consultas.quemprepara', verbose_name='Quem prepara as refeições'),
        ),
    ]
