# Generated by Django 5.0.3 on 2024-05-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_localrefeicao_quemprepara_tipoalcool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaGanhoPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Causa do ganho de peso',
                'verbose_name_plural': 'Causa do ganho de peso',
            },
        ),
        migrations.CreateModel(
            name='Complicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Sintomas gastrointestinais pós-cirurgicos',
                'verbose_name_plural': 'Sintomas gastrointestinais pós-cirurgicos',
            },
        ),
        migrations.CreateModel(
            name='OrientacaoDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Quem orientou a dieta?',
                'verbose_name_plural': 'Quem orientou a dieta?',
            },
        ),
        migrations.RemoveField(
            model_name='posoperatorio',
            name='complications',
        ),
        migrations.RemoveField(
            model_name='preoperatorio',
            name='diet_orientation',
        ),
        migrations.RemoveField(
            model_name='preoperatorio',
            name='weight_reason',
        ),
        migrations.AddField(
            model_name='posoperatorio',
            name='complications',
            field=models.ManyToManyField(to='consultas.complicacoes', verbose_name='Sintomas gastrointestinais pós-cirurgicos'),
        ),
        migrations.AddField(
            model_name='preoperatorio',
            name='diet_orientation',
            field=models.ManyToManyField(blank=True, to='consultas.orientacaodieta', verbose_name='Quem orientou a dieta?'),
        ),
        migrations.AddField(
            model_name='preoperatorio',
            name='weight_reason',
            field=models.ManyToManyField(to='consultas.causaganhopeso', verbose_name='Causa do ganho de peso'),
        ),
    ]
