# Generated by Django 5.0.3 on 2024-05-08 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_causaganhopeso_complicacoes_orientacaodieta_and_more'),
        ('registros', '0004_suplemento_alter_opcoesfamilia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Motivo de Não Atividade',
                'verbose_name_plural': 'Motivo de Não Atividade',
            },
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Atividade',
                'verbose_name_plural': 'Tipo de Atividade',
            },
        ),
        migrations.CreateModel(
            name='TipoDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de dieta',
                'verbose_name_plural': 'Tipo de dieta',
            },
        ),
        migrations.AlterModelOptions(
            name='preoperatorio',
            options={'verbose_name': 'Pré-Operatório', 'verbose_name_plural': 'Histórico de Excesso de peso e tratamento'},
        ),
        migrations.RemoveField(
            model_name='preoperatorio',
            name='sup_type',
        ),
        migrations.AddField(
            model_name='formbase',
            name='activity_type_motivo_outro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Se outro motivo, especifique:'),
        ),
        migrations.AddField(
            model_name='formbase',
            name='activity_type_outro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Se outra, especifique:'),
        ),
        migrations.AddField(
            model_name='formbase',
            name='alcoholic_type_outro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Se outra bebida, especifique:'),
        ),
        migrations.AddField(
            model_name='posoperatorio',
            name='improved_comorb_before',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Possuía comorbidades antes da cirurgia?'),
        ),
        migrations.AddField(
            model_name='preoperatorio',
            name='comorbidities_type_outro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Se outras, especifique:'),
        ),
        migrations.AddField(
            model_name='preoperatorio',
            name='type_diet',
            field=models.TextField(blank=True, max_length=255, verbose_name='Se sim, especifique'),
        ),
        migrations.AddField(
            model_name='preoperatorio',
            name='type_orientation',
            field=models.TextField(blank=True, max_length=255, verbose_name='Se Outros, especifique'),
        ),
        migrations.RemoveField(
            model_name='formbase',
            name='activity_type',
        ),
        migrations.AlterField(
            model_name='formbase',
            name='current_weight',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(60.0), django.core.validators.MaxValueValidator(400.0)], verbose_name='Peso atual'),
        ),
        migrations.AlterField(
            model_name='formbase',
            name='nutri_state',
            field=models.CharField(choices=[(1, 'Obesidade grau I'), (2, 'Obesidade grau II'), (3, 'Obesidade grau III')], max_length=2, null=True, verbose_name='Estado nutricional'),
        ),
        migrations.RemoveField(
            model_name='posoperatorio',
            name='improved_type',
        ),
        migrations.RemoveField(
            model_name='preoperatorio',
            name='do_diet',
        ),
        migrations.RemoveField(
            model_name='preoperatorio',
            name='sup_consumption',
        ),
        migrations.AddField(
            model_name='formbase',
            name='activity_type_motivo',
            field=models.ManyToManyField(blank=True, to='consultas.motivoatividade', verbose_name='Se não qual o motivo?'),
        ),
        migrations.AddField(
            model_name='formbase',
            name='activity_type',
            field=models.ManyToManyField(blank=True, to='consultas.tipoatividade', verbose_name='Qual atividade?'),
        ),
        migrations.AddField(
            model_name='posoperatorio',
            name='improved_type',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='comorbidadesMelhoraram', to='registros.comorbidade', verbose_name='Quais comorbidades melhoraram?'),
        ),
        migrations.AddField(
            model_name='preoperatorio',
            name='do_diet',
            field=models.ManyToManyField(to='consultas.tipodieta', verbose_name='Fez algum tipo de dieta para perda de peso?'),
        ),
        migrations.AddField(
            model_name='preoperatorio',
            name='sup_consumption',
            field=models.ManyToManyField(to='registros.suplemento', verbose_name='Consome algum suplemento alimentar'),
        ),
    ]
