# Generated by Django 5.0.3 on 2024-06-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_motivoatividade_tipoatividade_tipodieta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exames',
            name='has_exam',
            field=models.BooleanField(default=False, verbose_name='Tem Exame?'),
        ),
        migrations.AlterField(
            model_name='preoperatorio',
            name='type_diet',
            field=models.TextField(blank=True, max_length=255, verbose_name='Se Outros, especifique'),
        ),
    ]
